import os
from dotenv import load_dotenv

load_dotenv()

SLACK_APP_TOKEN = os.environ["SLACK_APP_TOKEN"]
SLACK_BOT_TOKEN = os.environ["SLACK_BOT_TOKEN"]
SLACK_SIGNING_SECRET = os.environ["SLACK_SIGNING_SECRET"]
PATH_TO_JSON_KEYFILE = os.environ["PATH_TO_JSON_KEYFILE"]
SPREAD_SHEET_KEY = os.environ["SPREAD_SHEET_KEY"]
MASTER_SHEET_KEY = os.environ["MASTER_SHEET_KEY"]
SLACK_WORKSPACE_TEAM_ID = os.environ["SLACK_WORKSPACE_TEAM_ID"]
ERROR_CHANNEL = os.environ["ERROR_CHANNEL"]

MYSQL_ROOT_PASSWORD = os.environ["MYSQL_ROOT_PASSWORD"]
MYSQL_DATABASE = os.environ["MYSQL_DATABASE"]
MYSQL_USER = os.environ["MYSQL_USER"]
MYSQL_PASSWORD = os.environ["MYSQL_PASSWORD"]
MYSQL_HOST = os.environ["MYSQL_HOST"]
